name: NoCollisionManager
version: 1.0.0
main: me.example.NoCollisionManager
api-version: 1.21
depend: [LuckPerms]
author: YourName
description: Gerencia colis達o de entidades por permiss達o via LuckPerms.

permissions:
  nocollision.bypass:
    description: Permite colis達o normal (bypass do modo sem colis達o).
    default: false
